id: A9EE2303E
title: A Combined Guru Yoga for Marpa, Mila, and Gampopa
type: translation
pechas:
- I68641881
- I7B1EBB71
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:01:13.113707
  last_modified_at: 2023-01-04 13:01:13.113729
  collections:
  - Marpa Lotsāwa Series
  - Works of Tibetan Masters
alignment_to_base:
  I68641881/A838: 07CC
  I7B1EBB71/2B2B: 07CC
